name: tiled
version: '1.1.3'
summary: Your free, easy to use and flexible tile map editor.
description: |
  Tiled is a free software level editor. It supports editing tile maps in
  various projections (orthogonal, isometric, hexagonal) and also supports
  building levels with freely positioned, rotated or scaled images or
  annotating them with objects of various shapes. 

grade: stable
confinement: strict

apps:
  tiled:
    command: desktop-launch ${SNAP}/usr/bin/tiled
    plugs:
      - desktop
      - unity7
      - x11
      - home

parts:
  tiled:
    plugin: qmake
    qt-version: qt5
    options:
      - PREFIX=/usr
      - CONFIG+=release
    source: .
    build-packages:
      - build-essential
      - qttools5-dev
      - qttools5-dev-tools
    after: [desktop-qt5]
